config/routes.rb
Rails.application.routes.draw do



   # 管理者　admin
     namespace :admin do
     # 管理者のセッション管理
     devise_for :admins, skip: [:confirmations, :passwords, :registrations, :unlocks]
      # 商品のルーティング
      resources :items, only: [:new, :create, :edit, :update, :index, :show]
     # 注文のルーティング
      resources :orders, only: [:index, :show, :update]
     # 注文商品のルーティング
      resources :order_items, only: [:update]
     # 顧客情報
      resources :customers, only: [:index, :show, :edit, :update]
     # ジャンル
      resources :genres, only: [:index, :create, :edit, :update]
     #検索機能
     get '/search', to: 'searches#search'
     end


   #顧客　customers

   # 商品のルーティング
   scope module: :public do
     root to: 'items#top'
     get '/search', to: 'searches#search'
     get '/about' => 'items#about'
     resources :items, only: [:index, :show]

     # カートのルーティング
     resources :cart_items, only: [:index, :create, :update, :destroy]
     delete '/all_destroy' => 'cart_items#all_destroy'

     # 注文のルーティング
     resources :orders, only: [:new]
     post 'orders/confirm' => 'orders#confirm'
     post 'orders' => 'orders#create'
     get 'orders' => 'orders#index'
     get 'order/:id' => 'orders#show', as: 'show_order'
     get 'orders/done' => 'orders#done'

     # 顧客情報
     get 'customers/my_page' => 'customers#show'
     get 'customers/edit' => 'customers#edit'
     patch 'customers/edit' => 'customers#update'
     get 'customers/unsubscribe' => 'customers#unsubscribe'
     patch 'customers/withdraw' => 'customers#withdraw'

     # デバイスのカスタマーのルーティング
     devise_for :customers, controllers: {
         sessions: 'public/sessions',
         registrations: 'public/registrations'
       }

     # 配送先のルーティング
     get 'customers/locations' => 'locations#index', as: 'locations'
     post 'customers/locations' => 'locations#create'
     get 'customers/locations/:id/edit' => 'locations#edit', as: 'edit_locations'
     patch 'customers/locations/:id/edit' => 'locations#update'
     delete 'customers/locations/:id' => 'locations#destroy', as: 'destroy_locations'

   end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def self.search_for(content)
        Customer.where('last_name LIKE ?', '%'+content+'%').or(Customer.where('first_name LIKE ?', '%'+content+'%'))
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render 'edit'
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_active)
    end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12 px-sm-0, content'>
    <span class="title">　会員一覧　</span>
    <table cellpadding="10">
      <!--colgroupはtdでcolspanを適用させるために記載-->
      <colgroup>
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
      </colgroup>
      <thead>
        <tr style="background-color: #EEEEEE;">
          <th colspan="1">会員ID</th>
          <th colspan="2">氏名</th>
          <th colspan="5">メールアドレス</th>
          <th colspan="2">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% customers.each do |customer| %>
        <tr>
          <td colspan="1"><%= customer.id %></td>
          <td colspan="2">
            <%= link_to (customer.last_name + customer.first_name), admin_customer_path(customer), class: "customer_#{customer.id}" %>
          </td>
          <td colspan="5"><%= customer.email %></td>
          <td colspan="2">
            <% if customer.is_active %>
              <div style="color: green;">有効</div>
            <% else %>
              <div style="color: #CCCCCC">退会</div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
   
  </div>
</div>


<style>
  .content{
    padding-top: 50px;
    padding-bottom: 50px;
  }
  .title{
    background-color: #EEEEEE;
    font-size: 20px;
    font-family: serif;
    margin-left: 10%;
  }
  table{
    width: 70%;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
  }
  tr{
    /*上下だけ囲む時の記述*/
    border-width: 1px 0;
    border-color: #CCCCCC;
    border-style: solid;
  }
  .pagination{
    justify-content: center;
    padding-top: 10px;
  }
</style>

app/views/admin/customers/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12 px-sm-0, content'>

    <% if @customer.errors.any? %>
      <div id="error explanation">
        <h3 style="color: red;"><%= @customer.errors.count %> error prohibited this obj from being saved:</h3>
          <ul style="color: red;">
            <% @customer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      </div>
    <% end %>

    <span>　会員情報編集　</span>
    <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>
      <table cellpadding="10">
        <!--colgroupはtdでcolspanを適用させるために記載-->
        <colgroup>
          <col style="width: 25%;">
          <col style="width: 25%;">
          <col style="width: 25%;">
          <col style="width: 25%;">
        </colgroup>
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %></t>
          <td><%= f.text_field :first_name %></td>
          <td></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana %></td>
          <td><%= f.text_field :first_name_kana %></td>
          <td></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postal_code %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>住所</td>
          <td colspan="3"><%= f.text_field :address, :size=>"70" %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :phone_number %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_active, :true, checked: true %>
            <%= f.label :is_active, "有効", {value: :true} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会", {value: :false} %>
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "　変更を保存　", class: "btn btn-outline-success" %></td>
          <td></td>
          <td></td>
        </tr>
      </table>
    <% end %>
    </div>
  </div>
</div>

<style>
  .content{
    padding-top: 30px;
    padding-bottom: 30px;
  }
  span{
    margin-left: 30px;
    background-color: #EEEEEE;
    font-size: 20px;
    font-family: serif;
  }
  table{
    margin-top: 20px;
    width: 90%;
  }
</style>

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12 px-sm-0, content'>
    <span class="title">　会員一覧　</span>
    <table cellpadding="10">
      <!--colgroupはtdでcolspanを適用させるために記載-->
      <colgroup>
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
        <col style="width: 10%;">
      </colgroup>
      <thead>
        <tr style="background-color: #EEEEEE;">
          <th colspan="1">会員ID</th>
          <th colspan="2">氏名</th>
          <th colspan="5">メールアドレス</th>
          <th colspan="2">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td colspan="1"><%= customer.id %></td>
          <td colspan="2">
            <%= link_to (customer.last_name + customer.first_name), admin_customer_path(customer), class: "customer_#{customer.id}" %>
          </td>
          <td colspan="5"><%= customer.email %></td>
          <td colspan="2">
            <% if customer.is_active %>
              <div style="color: green;">有効</div>
            <% else %>
              <div style="color: #CCCCCC">退会</div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination"><%= paginate @customers %></div>
    </div>
  </div>
</div>


<style>
  .content{
    padding-top: 30px;
    padding-bottom: 30px;
  }
  .title{
    background-color: #EEEEEE;
    font-size: 20px;
    font-family: serif;
    margin-left: 10%;
  }
  table{
    width: 70%;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
  }
  tr{
    /*上下だけ囲む時の記述*/
    border-width: 1px 0;
    border-color: #CCCCCC;
    border-style: solid;
  }
  .pagination{
    justify-content: center;
    padding-top: 10px;
  }
</style>

app/views/admin/customers/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12 px-sm-0, content'>
    <span class="title">　<%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細　</span>

    <table cellpadding="10">
      <!--colgroupはtdでcolspanを適用させるために記載-->
      <colgroup>
        <col style="width: 25%;">
        <col style="width: 25%;">
        <col style="width: 25%;">
        <col style="width: 25%;">
      </colgroup>
      <tr>
        <td>会員ID</td>
        <td colspan="3"><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <!--&emsp;は空白の役割-->
        <td colspan="3"><%= @customer.last_name %>&emsp;<%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td colspan="3"><%= @customer.last_name_kana %>&emsp;<%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td colspan="3"><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td colspan="3"><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td colspan="3"><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td colspan="3"><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td colspan="3">
          <% if @customer.is_active %>
            <div style="color: green;">有効</div>
          <% else %>
            <div style="color: #CCCCCC">退会</div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to '　編集する　', edit_admin_customer_path(@customer), class: "btn btn-outline-success" %></td>
        <td><%= link_to '　注文履歴一覧を見る　', admin_orders_path, class: "btn btn-outline-primary" %></td>
        <td></td>
      </tr>
    </table>
    </div>
  </div>
</div>


<style>
  .content{
    padding-top: 30px;
    padding-bottom: 30px;
  }
  .title{
    background-color: #EEEEEE;
    font-size: 20px;
    font-family: serif;
  }
  table{
    width: 90%;
    margin-top: 20px;
  }
</style>