config/routes.rb
Rails.application.routes.draw do



   # 管理者　admin
     namespace :admin do
     # 管理者のセッション管理
     devise_for :admins, skip: [:confirmations, :passwords, :registrations, :unlocks]
      # 商品のルーティング
      resources :items, only: [:new, :create, :edit, :update, :index, :show]
     # 注文のルーティング
      resources :orders, only: [:index, :show, :update]
     # 注文商品のルーティング
      resources :order_items, only: [:update]
     # 顧客情報
      resources :customers, only: [:index, :show, :edit, :update]
     # ジャンル
      resources :genres, only: [:index, :create, :edit, :update]
     #検索機能
     get '/search', to: 'searches#search'
     end


   #顧客　customers

   # 商品のルーティング
   scope module: :public do
     root to: 'items#top'
     get '/search', to: 'searches#search'
     get '/about' => 'items#about'
     resources :items, only: [:index, :show]

     # カートのルーティング
     resources :cart_items, only: [:index, :create, :update, :destroy]
     delete '/all_destroy' => 'cart_items#all_destroy'

     # 注文のルーティング
     resources :orders, only: [:new]
     post 'orders/confirm' => 'orders#confirm'
     post 'orders' => 'orders#create'
     get 'orders' => 'orders#index'
     get 'order/:id' => 'orders#show', as: 'show_order'
     get 'orders/done' => 'orders#done'

     # 顧客情報
     get 'customers/my_page' => 'customers#show'
     get 'customers/edit' => 'customers#edit'
     patch 'customers/edit' => 'customers#update'
     get 'customers/unsubscribe' => 'customers#unsubscribe'
     patch 'customers/withdraw' => 'customers#withdraw'

     # デバイスのカスタマーのルーティング
     devise_for :customers, controllers: {
         sessions: 'public/sessions',
         registrations: 'public/registrations'
       }

     # 配送先のルーティング
     get 'customers/locations' => 'locations#index', as: 'locations'
     post 'customers/locations' => 'locations#create'
     get 'customers/locations/:id/edit' => 'locations#edit', as: 'edit_locations'
     patch 'customers/locations/:id/edit' => 'locations#update'
     delete 'customers/locations/:id' => 'locations#destroy', as: 'destroy_locations'

   end



end

app/models/order.rb
class Order < ApplicationRecord

  validates :address, :name, presence: true


 
  
   has_many :order_items, dependent: :destroy
   belongs_to :customer, optional: true
   
   enum order_status: { wait: 0, payment: 1, make: 2, preparing: 3, done: 4 }
   enum payment: { card: 0, bank: 1 }
 
  
  VALID_POSTAL_CODE_REGEX =  /\A\d{7}\z/  #\Aから始まり\zに終わる\d{7}7桁の数字
  validates :postal_code, presence: true, format: { with: VALID_POSTAL_CODE_REGEX }
   
  def subtotal
		order_items.to_a.sum { |item| item.subtotal }
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin_admin!
  
  def index
    @orders=Order.page(params[:page]).per(10)
  end

  def show
    @order =Order.find(params[:id])
    order_items = @order.order_items
    @total = order_items.inject(0) { |sum, item| sum + item.sum_of_price }
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    #   注文ステータスと制作ステータスの紐付け
     # paramsのデータを取得する記述(enumの場合は文字列で出力される)
    # p params[:order][:order_status]　エラー文も出ずわからない際にpで定義を行うとターミナルに出力される
    if params[:order][:order_status] == "payment"
      @order.order_items.update(product_status: "make_wait")
    end
    redirect_to admin_order_path(@order.id)
  end
  
  private
  def order_params
    params.require(:order).permit(:total_price,:payment,:order_status,:postage,:name,:postal_code,:address)
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
    <% if flash[:notice] %>
     <div class="alert alert-success" role="alert">
       <p class="notice text-center" style="color:green;"><%= flash[:notice] %></p>
     </div>
      <% end %>
      <h3 class="mt-5 mb-3">
       <span class="bg-light">　注文履歴一覧　</span>
      </h3>
      <div class="row　justify-content-md-center">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>購入日時</th>
              <th>購入者</th>
              <th>注文個数</th>
              <th>注文ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <!--作成日時の表示を日本時間かつ、自分で決める（https://qiita.com/tomo_k09/items/e4f19947d35890500492）。.to_sで整数に。(:datetime_jp)はconfig/initializersにて作成したファイルで管理している-->
                <td>
                  <%= link_to admin_order_path(order.id) do %>
                    <%= order.created_at.to_s(:datetime_jp) %>
                  <% end %>
                </td>
                <td><%= order.name %></td>
                <!--注文個数の合計を表示[.sum]が合計(:quantity)が今回合計するカラム-->
                <td><%= order.order_items.sum(:quantity) %></td>
                <td><%= order.order_status_i18n %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
</div>
<div class="pagination pagination-sm justify-content-center mb-5">
    <%= paginate @orders %></div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
      <h3 class="head-line mt-5 mb-4 ml-5">
         <span class="bg-light">　注文履歴詳細　</span>
      </h3>
      <div class="row">
         <p class="col-md-2">購入者</p>
         <p class="col-md-10">
            <%= link_to admin_customer_path(@order.customer_id) do %>
               <%= @order.customer.last_name %> <%= @order.customer.first_name %>
            <% end %>
         </p>
      </div>
         
      <div class="row">
         <p class="col-md-2">注文日</p>
         <p class="col-md-10"><%= @order.created_at.to_s(:date_jp) %></p>
      </div>
        
      <div class="row">
         <p class="col-md-2">配送先</p>
         <p class="col-md-10">〒<%= @order.postal_code.to_s.insert(3, "-") %> <%= @order.address %></p>
      </div>
        
      <div class="row">
         <p class="col-md-2"></p>
         <p class="col-md-10"><%= @order.name %></p>
      </div>
      
      <div class="row">
         <p class="col-md-2">支払い方法</p>
         <p class="col-md-10"><%= @order.payment_i18n %></p>
      </div>

      <div class="row">
         <p class="col-md-2">注文ステータス</p>
         <div class="col-md-10">
            <%= form_with model: @order, url:admin_order_path(@order.id), method: :patch, local: true do | f | %> 
               <%= f.select :order_status, options_for_select_from_enum(Order, :order_status) %>
               <%= f.submit '更新',class: 'btn btn-success ml-4' %>
            <% end %>
         </div>
      </div>
      <div class="row mt-5">
         <div class="col-md-8">
            <table class="table table-striped table-hover">
               <thead>
                  <tr>
                     <th>商品名</th>
                     <th>単価(税込)</th>
                     <th>数量</th>
                     <th>小計</th>
                     <th>制作ステータス</th>
                  </tr>
               </thead>
               <tbody>
                  <% @order.order_items.each do |order_item| %>
                     <tr>
                        <td><%= order_item.item.name %></td>
                        <td><%= order_item.taxin_price.to_s(:delimited) %></td>
                        <td><%= order_item.quantity %></td>
                        <!--モデルに小計を呼び出すコード-->
                        <td>
                           <%= order_item.subtotal.to_s(:delimited) %>
                        </td>
                        <td>
                           <%= form_with model: order_item, url:admin_order_item_path(order_item.id), method: :patch, local: true do | f | %> 
                              <%#= f.select :product_status, options_for_select_from_enum(OrderItem, :product_status) %>
                              <%= f.select :product_status, OrderItem.product_statuses.keys.map {|k| [I18n.t("enums.order_item.product_status.#{k}"), k]} %>
                              <%= f.submit '更新',class: 'btn btn-success ml-2' %>
                           <% end %>
                        </td>
                     </tr>
                  <% end %>
               </tbody>
            </table>
         </div>
         <div class="col-md-4 d-flex align-items-end ">
            <div class="ml-5">
               <!--モデルに小計の計算の定義-->
               <p>商品合計　　　<%= @order.subtotal.to_s(:delimited) %>円</p>
               <p>送料　　　　　<%= @order.postage %>円</p>
               <!--コントローラで合計金額の定義-->
               <p>請求金額合計　<%= @order.total_price.to_s(:delimited) %>円</p>
            </div>
         </div>
      </div>
</div>