config/routes.rb
Rails.application.routes.draw do



   # 管理者　admin
     namespace :admin do
     # 管理者のセッション管理
     devise_for :admins, skip: [:confirmations, :passwords, :registrations, :unlocks]
      # 商品のルーティング
      resources :items, only: [:new, :create, :edit, :update, :index, :show]
     # 注文のルーティング
      resources :orders, only: [:index, :show, :update]
     # 注文商品のルーティング
      resources :order_items, only: [:update]
     # 顧客情報
      resources :customers, only: [:index, :show, :edit, :update]
     # ジャンル
      resources :genres, only: [:index, :create, :edit, :update]
     #検索機能
     get '/search', to: 'searches#search'
     end


   #顧客　customers

   # 商品のルーティング
   scope module: :public do
     root to: 'items#top'
     get '/search', to: 'searches#search'
     get '/about' => 'items#about'
     resources :items, only: [:index, :show]

     # カートのルーティング
     resources :cart_items, only: [:index, :create, :update, :destroy]
     delete '/all_destroy' => 'cart_items#all_destroy'

     # 注文のルーティング
     resources :orders, only: [:new]
     post 'orders/confirm' => 'orders#confirm'
     post 'orders' => 'orders#create'
     get 'orders' => 'orders#index'
     get 'order/:id' => 'orders#show', as: 'show_order'
     get 'orders/done' => 'orders#done'

     # 顧客情報
     get 'customers/my_page' => 'customers#show'
     get 'customers/edit' => 'customers#edit'
     patch 'customers/edit' => 'customers#update'
     get 'customers/unsubscribe' => 'customers#unsubscribe'
     patch 'customers/withdraw' => 'customers#withdraw'

     # デバイスのカスタマーのルーティング
     devise_for :customers, controllers: {
         sessions: 'public/sessions',
         registrations: 'public/registrations'
       }

     # 配送先のルーティング
     get 'customers/locations' => 'locations#index', as: 'locations'
     post 'customers/locations' => 'locations#create'
     get 'customers/locations/:id/edit' => 'locations#edit', as: 'edit_locations'
     patch 'customers/locations/:id/edit' => 'locations#update'
     delete 'customers/locations/:id' => 'locations#destroy', as: 'destroy_locations'

   end



end

app/models/genre.rb
class Genre < ApplicationRecord

has_many:items
validates :name,presence:true
# validates :name, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin_admin!
  
  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def create
    @genre=Genre.new(genre_params)
    if @genre.save
    redirect_to request.referer,notice:"登録完了しました！"
    else
    render :index
    end
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
    redirect_to admin_genres_path,notice:"更新完了しました！"
    else
    reder :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form.html.erb
<div class="form-group row">
    <%= f.label:"ジャンル名",class:"col-sm-2"%>
    <%= f.text_field :name,placeholder:"ジャンル名",class:"form-control col-sm-4",required:true%>

app/views/admin/genres/edit.html.erb
<div class="container" style="margin-bottom:80px;">


<div class="head-line" style="margin-bottom:60px;">
<h2 class="head-line">ジャンル編集</h2></div>


<%= form_with model:@genre,url:admin_genre_path(@genre.id),local:true do |f| %>
<%= render "form", f: f %>
 <%= f.submit "　変更を保存　" ,class:"btn btn-success offset-1 pl-20"%>
</div>   
<% end %>




</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
    
<!--エラーメッセージ　マージ前なのでコメントアウト-->

 <!--登録、更新完了　フラッシュメッセージ-->
<% if flash[:notice] %>
 <div class="alert alert-success" role="alert">
 <p class="notice text-center" style="color:green;"><%= flash[:notice] %></p></div>
<% end %>
    
    
<div class="head-line" style="margin-bottom:60px;">
<h2 class="head-line">ジャンル一覧・追加</h2></div>

<!--ジャンルの新規登録、編集の共有部は部分テンプレです-->
<%= form_with model:@genre,url:admin_genres_path,local:true do |f| %>
<%= render "form", f: f %>
 <%= f.submit "　新規登録　" ,class:"btn btn-success offset-1 pl-20"%>
</div>
<!--このdiv閉じは部分テンプレの続きです。-->
<% end %>

<div class="col-md-5" style="margin-top:60px;">
    <table class="table table-hover">
        <thead class="table-secondary">
            <tr>
                <th> ジャンル</th>
                <th></th>
                
            </tr>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
        <tr>
            <th><%=genre.name%></th>
            <th class="text-right"><%= link_to "編集する",edit_admin_genre_path(genre),class:"btn btn-success"%></th>
        </tr>
        <% end %>
        </tbody>
    </table>
</div>


</div>
</div>