config/routes.rb
Rails.application.routes.draw do



   # 管理者　admin
     namespace :admin do
     # 管理者のセッション管理
     devise_for :admins, skip: [:confirmations, :passwords, :registrations, :unlocks]
      # 商品のルーティング
      resources :items, only: [:new, :create, :edit, :update, :index, :show]
     # 注文のルーティング
      resources :orders, only: [:index, :show, :update]
     # 注文商品のルーティング
      resources :order_items, only: [:update]
     # 顧客情報
      resources :customers, only: [:index, :show, :edit, :update]
     # ジャンル
      resources :genres, only: [:index, :create, :edit, :update]
     #検索機能
     get '/search', to: 'searches#search'
     end


   #顧客　customers

   # 商品のルーティング
   scope module: :public do
     root to: 'items#top'
     get '/search', to: 'searches#search'
     get '/about' => 'items#about'
     resources :items, only: [:index, :show]

     # カートのルーティング
     resources :cart_items, only: [:index, :create, :update, :destroy]
     delete '/all_destroy' => 'cart_items#all_destroy'

     # 注文のルーティング
     resources :orders, only: [:new]
     post 'orders/confirm' => 'orders#confirm'
     post 'orders' => 'orders#create'
     get 'orders' => 'orders#index'
     get 'order/:id' => 'orders#show', as: 'show_order'
     get 'orders/done' => 'orders#done'

     # 顧客情報
     get 'customers/my_page' => 'customers#show'
     get 'customers/edit' => 'customers#edit'
     patch 'customers/edit' => 'customers#update'
     get 'customers/unsubscribe' => 'customers#unsubscribe'
     patch 'customers/withdraw' => 'customers#withdraw'

     # デバイスのカスタマーのルーティング
     devise_for :customers, controllers: {
         sessions: 'public/sessions',
         registrations: 'public/registrations'
       }

     # 配送先のルーティング
     get 'customers/locations' => 'locations#index', as: 'locations'
     post 'customers/locations' => 'locations#create'
     get 'customers/locations/:id/edit' => 'locations#edit', as: 'edit_locations'
     patch 'customers/locations/:id/edit' => 'locations#update'
     delete 'customers/locations/:id' => 'locations#destroy', as: 'destroy_locations'

   end



end

app/views/layouts/_admin_search.html.erb
<div class="serch_form">
    <%= form_with url: admin_search_path,method: :get, local: true do |f| %>
    <%= f.text_field :content,placeholder:"Search"%>
    <%= f.select :model,options_for_select({"商品"=>"item","顧客"=>"customer"})%>
    <%= f.submit'検索'%>
    <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> 保存されていません</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <footer class="pt-5 pb-4", style="background-color:#FFFAFA;">
  <div class="container">
  <footer class="text-center">CopyRight karuizawa</footer>
  </div>
  </footer>


<style>
  footer{
    margin-top: auto;
  }
</style>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#FFFAFA;">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag 'logo1.png', size: '200x80' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <!--カスタマーログイン後は以下のメニューが表示されるようにしてください。-->
       <% if customer_signed_in? %>
          <li class="nav-item"><%= link_to "マイページ", customers_my_page_path,class:'nav-link btn btn-outline-danger'%></li>
          <li class="nav-item  pl-4"><%= link_to "商品一覧", items_path,class:'nav-link btn btn-outline-danger'%></li>
           <li class="nav-item  pl-4"><%= link_to "カート", cart_items_path,class:'nav-link btn btn-outline-danger'%></li>
          <li class="nav-item pl-4"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:'nav-link btn btn-outline-danger'%></li>
          <li><div class="input-group pl-4">
          <%= render 'layouts/search' %>
          </div></li>



        <!--管理者ログインしている場合-->

        <% elsif admin_admin_signed_in? %>
        <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class:'nav-link btn btn-outline-danger'%></li>
        <li class="nav-item pl-4"><%= link_to "会員一覧", admin_customers_path, class:'nav-link btn btn-outline-danger'%></li>
        <li class="nav-item pl-4"><%= link_to "注文履歴一覧", admin_orders_path, class:'nav-link btn btn-outline-danger'%></li>
        <li class="nav-item pl-4"><%= link_to "ジャンル一覧", admin_genres_path, class:'nav-link btn btn-outline-danger'%></li>
        <li class="nav-item pl-4"><%= link_to "ログアウト", destroy_admin_admin_session_path, method: :delete, class:'nav-link btn btn-outline-danger'%></li>
        <li><div class="input-group pl-4">

          <%= render 'layouts/admin_search' %>


          </div></li>
          
        <!--ログインしてない-->
        <% else %>
          <li class="nav-item"><%= link_to "About", about_path,class:'nav-link btn btn-outline-danger'%></li>
          <li class="nav-item pl-4"><%= link_to "商品一覧", items_path,class:'nav-link btn btn-outline-danger'%></li>
          <li class="nav-item pl-4"><%= link_to "新規登録", new_customer_registration_path,class:'nav-link btn btn-outline-danger'%></li>
          <li class="nav-item pl-4"><%= link_to "ログイン", new_customer_session_path,class:'nav-link btn btn-outline-danger'%></li>
          <li><div class="input-group pl-4">
          <%= render 'layouts/search' %>
          </div></li>
        <% end %>


        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="serch_form">
    <%= form_with url: search_path,method: :get, local: true do |f| %>
    <%= f.text_field 'search[value]',placeholder:"商品名を検索"%>
    <%= f.submit'検索'%>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
   <div class="wrapper">




    <main>
    <%= yield %>
    </main>
    <!--フッターー部分を部分テンプレにしました-->
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>


<style>
  .wrapper{
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  }
</style>